### ISSUE TITLE
Rendering of mathematical equations

### ISSUE THREAD

**Issue by martinjaeger** [LibreSolar/learn.libre.solar#1]
The mathjax plugin is already installed as [described in VuePress documentation](https://vuepress.github.io/en/plugins/mathjax/):
https://github.com/LibreSolar/learn.libre.solar/blob/086e2c88ac7ad2c597a55c702ad1b699dfd8cdc3/docs/.vuepress/config.js#L6-L11

Unfortunately, math formula are not rendered correctly. Example for test:
https://learn.libre.solar/development/dcdc_converter.html

**Comment by martinjaeger** [comment]
@jurra do you have an idea what could be the problem?

**Comment by jurra** [comment]
Hi Martin I will check it when i get home. Today i am working. I havent
work with this module. It looks like some config issue.

**Comment by jurra** [comment]
I solved this issue by updating vuepress and changing the package to vuepress-plugin-latex. I tried to push my changes to my own branch. [Check the pull request](https://github.com/LibreSolar/learn.libre.solar/pull/3). After testing if it works fine for you (locally) and also on deployment, close this issue ;)

**Comment by martinjaeger** [comment]
Very cool!

It's strange that you can't push. Checked again, you have write (incl. push) permission. Or otherwise try with a pull-request.

**Comment by jurra** [comment]
Now I pushed, its ok ;)

**Comment by martinjaeger** [comment]
Solved after upgrade of VuePress to v1.0.
